source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'GoogleBooksApp' do
    use_frameworks!
    
    pod 'OAuthSwift', '~> 2.0.0'
    pod 'KeychainSwift', '~> 16.0.1'
    pod 'R.swift', '~> 5.0.3'
    pod 'Swinject', '~> 2.6.2'
    pod 'Moya', '~> 13.0.1'
    pod 'NVActivityIndicatorView', '~> 4.7.0'
    pod 'Kingfisher', '~> 5.7.0'
    pod 'DZNEmptyDataSet', '~> 1.8.1'
    pod 'DTTableViewManager', '~> 6.6.0'
    pod 'PluggableAppDelegate', '~> 1.3.0'
    
    pod 'LightRoute', :git => 'https://github.com/SpectralDragon/LightRoute.git'
    pod 'SwinjectStoryboard', :git => 'https://github.com/mdyson/SwinjectStoryboard.git'
end
